AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM CloudFormation Template'

Resources:
  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'BCS_CloudFormation'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'